select
    channel_id,
    ts,
    author_id,
    author_kind,
    bot_id,
    app_id,
    parent_user_id,
    subtype,
    thread_root_ts,
    is_reply,
    is_broadcast,
    posted_at,
    edited_at,
    reply_count,
    reply_users_count,
    latest_reply_ts,
    reaction_count,
    reactor_count,
    file_count,
    text_length,
    mention_count,
    mentioned_ids,
    is_question,
    is_substantive,
    has_link,
    emoji_only,
    settled,
    first_seen_at as observed_at
from {{ source('archive', 'message') }}
where deleted_at is null
