CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS app;

-- pipeline
CREATE ROLE pipeline_writer LOGIN;
GRANT USAGE ON SCHEMA raw TO pipeline_writer;
GRANT INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA raw TO pipeline_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT INSERT, SELECT, UPDATE ON TABLES TO pipeline_writer;

-- dbt
CREATE ROLE dbt_owner LOGIN;
GRANT USAGE ON SCHEMA raw, app TO dbt_owner;
GRANT SELECT ON ALL TABLES IN SCHEMA raw, app TO dbt_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO dbt_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT ON TABLES TO dbt_owner;
GRANT ALL ON SCHEMA analytics TO dbt_owner;

-- rails
CREATE ROLE rails_app LOGIN;
GRANT ALL ON SCHEMA app TO rails_app;
GRANT USAGE ON SCHEMA analytics TO rails_app;

-- superset
CREATE ROLE superset_ro LOGIN;
GRANT USAGE ON SCHEMA analytics TO superset_ro;
