RELAY = "relay"
NEMO = "nemo"

APPS = (RELAY, NEMO)

NEEDS = {
    RELAY: ["RELAY_BOT_TOKEN", "RELAY_APP_TOKEN"],
    NEMO: ["NEMO_BOT_TOKEN", "NEMO_APP_TOKEN", "INTERNAL_LOG_CHANNEL_ID", "SLACK_TEAM_ID"],
}
