SHROUD = "shroud"
NEMO = "nemo"
SPINE = "spine"

APPS = (SHROUD, NEMO, SPINE)

NEEDS = {
    SHROUD: ["SHROUD_BOT_TOKEN", "SHROUD_APP_TOKEN"],
    NEMO: ["NEMO_BOT_TOKEN", "NEMO_APP_TOKEN", "FIREHOUSE_CHANNEL_ID"],
    SPINE: ["SLACK_BOT_TOKEN", "SLACK_APP_TOKEN"],
}
