select
    ds,
    source,
    total_members_count,
    total_claimed_count,
    full_members_count,
    guests_count,
    claimed_full_members_count,
    claimed_guests_count,
    total_full_members_count,
    total_guests_count,
    active_users_1d,
    active_users_7d,
    active_users_28d,
    writers_count_1d,
    writers_count_7d,
    writers_count_28d,
    readers_count_1d,
    readers_count_7d,
    messages_count_1d,
    messages_channels_count_from_apps_1d,
    messages_count_1d - coalesce(messages_channels_count_from_apps_1d, 0) as messages_from_members_1d,
    chats_count_1d,
    chats_channels_count_1d,
    chats_groups_count_1d,
    chats_dms_count_1d,
    chats_shared_channels_count_1d,
    coalesce(chats_channels_count_1d, 0) + coalesce(chats_groups_count_1d, 0) as channel_messages_1d,
    cursor_marks_channels_count_1d,
    cursor_marks_groups_count_1d,
    cursor_marks_dms_count_1d,
    cursor_marks_shared_channels_count_1d,
    files_count_1d,
    files_size,
    channels_count,
    users_channels_count
from {{ source('raw', 'team_stats_snapshot') }}
