version: 2

models:
  - name: dim_member
    columns:
      - name: user_id
        data_tests: [unique, not_null]
  - name: dim_channel
    columns:
      - name: channel_id
        data_tests: [unique, not_null]
  - name: fct_member_activity
    columns:
      - name: user_id
        data_tests: [not_null]
  - name: fct_channel_activity
    columns:
      - name: channel_id
        data_tests: [not_null]
  - name: fct_message
    columns:
      - name: ts
        data_tests: [not_null]
      - name: user_id
        data_tests: [not_null]
      - name: channel_id
        data_tests: [not_null]
  - name: fct_first_reply
    columns:
      - name: newcomer_id
        data_tests: [unique, not_null]
      - name: replier_id
        data_tests: [not_null]
